# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58dc9c574f486df0c491845d998066b276962b9b00fad2264066258fa2cbbac4b3f3e609daa94ec908fa6841351d6a7c0eb175ecc92467545de5dd7d3f060e61

test:
  secret_key_base: 4c159f2633f523a981d59c0df2570d7d393ad63f2566a964cb16251e668bde12acc3a164c3c3664a3a53a70765dae7a46df561bc3def5832c489829fd0a06c7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
